project_id = "lezqonvzqwpdpmyvpuvd"

[functions.generate-workout]
verify_jwt = false

[functions.generate-strength]
verify_jwt = false

[functions.generate-meals]
verify_jwt = false

[functions.create-notification]
verify_jwt = false
