project_id = "lezqonvzqwpdpmyvpuvd"

[functions.generate-workout]
verify_jwt = false

[functions.generate-strength]
verify_jwt = false

[functions.generate-meals]
verify_jwt = false

[functions.create-notification]
verify_jwt = false

[functions.parse-workout-image]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.analyze-workout]
verify_jwt = false

[functions.chat-rowing]
verify_jwt = false

[functions.critique-rowing]
verify_jwt = false

[functions.parse-erg-screen]
verify_jwt = false

[functions.predict-recruitment]
verify_jwt = false

[functions.generate-recruit-emails]
verify_jwt = false

[functions.parse-nutrition-label]
verify_jwt = false
