const TermsOfService = () => (
  <div className="min-h-screen bg-background text-foreground">
    <div className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-10">
        Last updated: May 27, 2026 &nbsp;·&nbsp;{" "}
        <a href="https://crewsync.app" className="underline hover:text-foreground">
          crewsync.app
        </a>
      </p>

      <section className="space-y-8 text-sm leading-relaxed">
        <div>
          <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
          <p>
            By creating an account or using CrewSync ("the Service"), you agree to be bound by
            these Terms of Service ("Terms"). If you do not agree, do not use the Service. We
            may update these Terms from time to time — continued use after changes constitutes
            acceptance. We will notify users of material changes by email.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">2. Age Requirements</h2>
          <p>
            <strong>Users under 13 are not permitted to use CrewSync.</strong> Users aged
            13–17 may use the Service only with verifiable parental or guardian consent, which
            must be obtained and documented by the coach or program administrator adding the
            athlete. By creating an account, you represent that you are at least 13 years old
            or have obtained required parental consent.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">3. Description of Service</h2>
          <p>
            CrewSync provides an AI-powered rowing training platform including erg performance
            tracking, AI-generated workout plans, recovery logging, team management tools, and
            coach-athlete communication features. The Service is provided for informational and
            training support purposes only.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">4. Limitation of Liability and No Warranty</h2>
          <p>
            <strong>
              CrewSync is not liable for athletic injuries, training decisions, or performance
              outcomes resulting from use of the Service or AI-generated training recommendations.
            </strong>{" "}
            All AI-generated training plans, workout recommendations, and performance analyses
            are generated by automated systems and are not a substitute for guidance from a
            qualified rowing coach or sports medicine professional.
          </p>
          <p className="mt-2">
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
            EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. CREWSYNC DOES NOT WARRANT
            THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES.
          </p>
          <p className="mt-2">
            IN NO EVENT SHALL CREWSYNC, ITS OPERATORS, OR AFFILIATES BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT
            NOT LIMITED TO PERSONAL INJURY, PROPERTY DAMAGE, OR LOSS OF DATA, ARISING FROM YOUR
            USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p className="mt-2">
            Recovery scores, wellness check-ins, and biometric data presented in the Service
            are for informational purposes only and are not medical advice. Injury logs in
            the Service are not medical records. Consult a qualified healthcare professional
            for any health or medical concerns.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">5. Intellectual Property</h2>
          <p>
            <strong>CrewSync owns the platform.</strong> All software, code, design, trademarks,
            and content created by CrewSync are the exclusive property of CrewSync and its
            operators. You may not copy, modify, distribute, or create derivative works from
            any part of the platform without written permission.
          </p>
          <p className="mt-2">
            <strong>You own your data.</strong> All personal data you enter — including erg
            scores, training logs, profile information, and uploaded files — belongs to you.
            CrewSync owns aggregate, anonymized insights derived from usage patterns across
            the platform, provided that individual users are never identifiable from such
            aggregate data. CrewSync will never sell individual user data to third parties.
          </p>
          <p className="mt-2">
            You grant CrewSync a limited, non-exclusive license to process and store your data
            solely for the purpose of providing the Service to you.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">6. Data Portability</h2>
          <p>
            You may export all your personal data at any time using the Export My Data feature
            in Account Settings. Exported data is provided in JSON format and includes your
            profile, all erg workouts and scores, recovery logs, wellness check-ins, and
            training plans. See our Privacy Policy for full details.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">7. Recruiting Features</h2>
          <p>
            CrewSync recruiting features connect athletes with college coaches. CrewSync does
            not guarantee any recruitment outcomes. Athletes are responsible for verifying their
            own NCAA, NAIA, and other governing body eligibility rules. Coaches using recruiting
            features are solely responsible for compliance with all applicable NCAA, NAIA, and
            other governing body recruiting regulations, including communication timing
            restrictions. CrewSync is not affiliated with the NCAA, NAIA, or any governing body.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">8. SafeSport and Coach-Athlete Communications</h2>
          <p>
            All coach-athlete messages sent through CrewSync are visible to the full coaching
            staff of the team in compliance with SafeSport guidelines. By using the messaging
            features, coaches and athletes acknowledge this transparency policy. CrewSync
            maintains a message audit log for SafeSport compliance purposes. Messages are
            never permanently deleted — they are archived and retained for compliance purposes.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">9. Subscriptions and Payments</h2>
          <p>
            Paid subscription features will be available beginning Fall 2026. The following
            policies will apply when payments are enabled:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Monthly subscriptions: no refunds after a billing period begins.</li>
            <li>Annual subscriptions: pro-rated refunds available within 30 days of payment.</li>
            <li>Cancellation: access continues until the end of the current billing period.</li>
            <li>Price changes: existing subscribers will receive 30 days notice before any price increase.</li>
            <li>Payment processing: handled by Stripe. CrewSync never stores raw credit card numbers.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">10. Termination</h2>
          <p>
            You may terminate your account at any time from Account Settings. CrewSync may
            suspend or terminate accounts that violate these Terms, engage in abusive behavior,
            or create legal risk for the platform. Upon termination, your personal data will
            be permanently deleted consistent with our Privacy Policy.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">11. Governing Law and Dispute Resolution</h2>
          <p>
            These Terms are governed by the laws of the Commonwealth of Massachusetts, without
            regard to conflict of law principles. Any disputes arising from these Terms or
            your use of the Service shall be resolved through binding arbitration under the
            rules of the American Arbitration Association, with proceedings conducted in
            Massachusetts. You waive the right to participate in class action lawsuits against
            CrewSync.
          </p>
          <p className="mt-2">
            Notwithstanding the above, either party may seek injunctive or other equitable
            relief in a court of competent jurisdiction in Massachusetts for violations of
            intellectual property rights.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">12. Contact</h2>
          <p>
            For questions about these Terms, contact:
          </p>
          <p className="mt-2 font-medium">
            Sam Weibust — CrewSync
            <br />
            <a href="mailto:sam.weibust@gmail.com" className="underline hover:text-foreground">
              sam.weibust@gmail.com
            </a>
          </p>
        </div>
      </section>
    </div>
  </div>
);

export default TermsOfService;
